### ISSUE TITLE
Reflection fails to find the changeLogs doesn't work with Java 11 plus Jacoco instrumentation

### ISSUE THREAD

**Issue by albert0815** [mongock/mongock#247]
Hi all,

Thanks for working on Mongock, this is definitly something which is required! We want to use it in our application which is based on Quarkus. Our first test seem to work fine, but we are having an issue which is occurring when using Mongock ChangeLog classes  and having Jacoco enabled for tracking code coverage.

Our current setup
We are using a listener to the StartupEvent provided by Quarkus to conduct the migration execution using the standalone runner:

```
    MongockStandalone.Runner runner =
        MongockStandalone.builder()
            .setDriver(driver)
            .addChangeLogsScanPackage("package")
            .setTrackIgnored(true)
            .setEnabled(true)
            .buildRunner();

    runner.execute();
```

This works fine when the actual application starts, but when classes are instrumented using the jacoco agent somehow Mongock is not able to find the ChangeLogs. In our pom.xml we have the agent dependency included:

```
        <dependency>
            <groupId>org.jacoco</groupId>
            <artifactId>org.jacoco.agent</artifactId>
            <classifier>runtime</classifier>
            <scope>test</scope>
            <version>0.8.5</version>
        </dependency>

```

I tried to debug this, what I can see is that the method fetchChangeLogs() in the ChangeLogService is not able to find any migration classes and returns an empty list. Not really sure what exactly fails. When comparing the generated class files using javap I found the major difference in a failing case is the jacoco additions. So I removed the jacoco agent to see whether the changelogs are executed and that worked fine. I do not understand why those changelogs are not found when the classes are instrumented by jacoco. I hope you can help me identifying the root cause of this problem.

Maybe this is similar to https://stackoverflow.com/questions/41542187/java-annotation-capturing-with-reflection-will-not-work-when-execuete-jacoco-pre ?

Thanks

**Comment by dieppa** [comment]
Hello, I am not sure this is related to Mongock itself, let us take a look over the week. ok?

**Comment by albert0815** [comment]
Hi @dieppa !

Thanks for getting back to me on this. Yes, I am also not sure whether it is related to Mongock itself. Personally I doubt that the issue itself is within Jacoco, but who knows... Maybe something in this reflection lib you are using, I saw the comment "// TODO remove dependency, do own method" :). I prepared a ready to use test case stripping down the problem to few classes, without Quarkus and the problem is reproduceable. 

You can clone this repo: https://github.com/albert0815/mongock-standalone-jacoco

If you run `mvn clean test` on that the existing test case will work fine. The jacoco configuration in the pom.xml is commented. If you enable that section in the pom.xml and rerun `mvn clean test` the test case will fail.

**Comment by dieppa** [comment]
I will check it out, thanks

**Comment by dieppa** [comment]
Sorry we have dealing with an issue that affected JHipster integration. We'll try to take a look to this during this week.

**Comment by albert0815** [comment]
Are you willing to look into this issue? I mean, Jacoco is not that uncommon I guess. Maybe you could at least check whether you think this is a bug in Mongock or not.

**Comment by dieppa** [comment]
Hello, yeah, being realistic we can take a look at this and tell you something by Monday. If that works for you.

**Comment by dieppa** [comment]
working on this. It seems to happen with Jacoco instrument goal + java 11. Either removing Jacoco instrument goal or using Java8, works fine.

We'll keep you updated

**Comment by dieppa** [comment]
We think we found a way to fix this issue. We expect to have a bugfix at the end of the day or tomorrow

**Comment by dieppa** [comment]
Hello @albert0815 ,

after taking a deeper look, we confirm that is related to Java 11 with Jacoco. Doesn't seem to be straight forward to fix. We'll create a issue specifically for this.

However, there is a workaround that should work for you meanwhile. Instead of provide the package name, you can add the  changeLog class directly:

```java
//...
    MongockStandalone.Runner runner =
        MongockStandalone.builder()
            .setDriver(driver)
//            .addChangeLogsScanPackage("xxx.migration")
                .addChangeLogClass(ChangeMongoDb.class)
            .setTrackIgnored(true)
            .setEnabled(true)
            .buildRunner();
//...
```

I know it's not ideal. We'll try to provide a more elegant solution as soon as we can.

**Comment by dieppa** [comment]
Issue happens when using Java 11 and adding Jacoco instrumentation to Jacoco maven plugin
```xml
<!-- ... -->
          <execution>
            <id>default-instrument</id>
            <goals>
              <goal>instrument</goal>
            </goals>
          </execution>
<!-- .. -->

```

**Comment by albert0815** [comment]
Thanks for looking into this. The workaround we were using in the meantime is to exclude the mongock migration packages from the coverage measurement. I don't like that as we are actually also implementing tests for the migration and coverage information would be interesting. The workaround you are suggesting is also a little cumbersome because our developers always would need to remember to add new migration classes to that builder statement. So we are hoping you can provide this more elegant solution soon :).

**Comment by albert0815** [comment]
This error does not occure when using online instrumentation.
