### ISSUE TITLE
mongodb-sync-v4-driver dependent on spring-boot ?

### ISSUE THREAD

**Issue by ChristofBuechi** [mongock/mongock#295]
As far as I understand, you basically provide a driver for using it with spring, and one to use it without spring. Unfortunately it turns out that the one for using standalone (mongodb-sync-v4-driver) also references to the springframework chain, as you can see in the following. Is there a way to use it without spring ? Preferable: org.mongodb:mongodb-driver-sync

---------------------------
\--- com.github.cloudyrock.mongock:mongodb-sync-v4-driver:4.3.3
     +--- com.github.cloudyrock.mongock:mongock-driver-core:4.3.3
     |    +--- com.github.cloudyrock.mongock:mongock-driver-api:4.3.3
     |    |    +--- com.github.cloudyrock.mongock:mongock-api:4.3.3
     |    |    |    +--- org.springframework.boot:spring-boot-autoconfigure:2.3.7.RELEASE
     |    |    |    |    \--- org.springframework.boot:spring-boot:2.3.7.RELEASE
     |    |    |    |         +--- org.springframework:spring-core:5.2.12.RELEASE
     |    |    |    |         \--- org.springframework:spring-context:5.2.12.RELEASE
     |    |    |    |              +--- org.springframework:spring-aop:5.2.12.RELEASE
     |    |    |    |              |    +--- org.springframework:spring-beans:5.2.12.RELEASE
     |    |    |    |              |    |    \--- org.springframework:spring-core:5.2.12.RELEASE
     |    |    |    |              |    \--- org.springframework:spring-core:5.2.12.RELEASE
     |    |    |    |              +--- org.springframework:spring-beans:5.2.12.RELEASE
     |    |    |    |              +--- org.springframework:spring-core:5.2.12.RELEASE
     |    |    |    |              \--- org.springframework:spring-expression:5.2.12.RELEASE
     |    |    |    |                   \--- org.springframework:spring-core:5.2.12.RELEASE
     |    |    |    \--- org.springframework.boot:spring-boot-configuration-processor:2.3.7.RELEASE
     |    |    +--- com.github.cloudyrock.mongock:mongock-utils:4.3.3
     |    |    |    \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.29
     |    |    \--- javax.inject:javax.inject:1
     |    +--- com.github.cloudyrock.mongock:mongock-api:4.3.3 (*)
     |    +--- com.github.cloudyrock.mongock:mongock-utils:4.3.3 (*)
     |    \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.29
     +--- com.github.cloudyrock.mongock:mongock-api:4.3.3 (*)
     \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.29

**Comment by dieppa** [comment]
We'll look a it. Thanks!

**Comment by dieppa** [comment]
In order to keep you updated. We expect to have this sorted in the next week. 

Thanks!

**Comment by vkrylov** [comment]
Is there any updates about the issue?

**Comment by dieppa** [comment]
Hello, sorry for the late reply.

We have fixed this as part of the version 5. Our expectation its to have a RC middle/end of August.
