### ISSUE TITLE
dup key: { executionId: null, author: "author", changeId: null }

### ISSUE THREAD

**Issue by sam-element** [mongock/mongock#337]
**Describe the bug** 

Hi, 

No matter what I do, I always get this error.
`Caused by: org.springframework.dao.DuplicateKeyException: E11000 duplicate key error collection: db-dev.mongockChangeLog index: executionId_1_author_1_changeId_1 dup key: { executionId: null, author: "author", changeId: null }; nested exception is com.mongodb.MongoWriteException: E11000 duplicate key error collection: db-dev.mongockChangeLog index: executionId_1_author_1_changeId_1 dup key: { executionId: null, author: "author", changeId: null }`

I spent hours finding out that the index created in **mongockChangeLog** collection is `executionId` + `author` + `changeId`, (the naming is camel case). However, the fields in Document are `execution_id` and `change_id` (in snake case, which is set by `spring.data.mongodb.field-naming-strategy=org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy`). So the index will not work and always throw that error because it can't find `executionId` and `changeId`. I tried to set `index-creation` to `false` but a new exception pops up:

`Caused by: io.changock.migration.api.exception.ChangockException: Index creation not allowed, but not created or wrongly created for collection mongockLock`. 

Btw, I always delete both `mongockChangeLog` and `mongockLock` collections before testing my changes.

I'm officially f**ked by this lib. However, thanks for your dedication to the mongodb migration tool. 

**To Reproduce**

Steps and conditions to reproduce the behavior:
 - Conditions:
    - Framework and libraries versions. Especially those that affect directly to Mongock(Spring, Spring data, MongoDB driver, etc.):
```
implementation(platform("com.github.cloudyrock.mongock:mongock-bom:4.1.18"))
implementation("com.github.cloudyrock.mongock:mongock-spring-v5")
implementation("com.github.cloudyrock.mongock:mongodb-springdata-v3-driver")
```

other relevant should be:
```
plugins {
    id("org.springframework.boot") version "2.4.0"
}
```

and

```
 implementation("org.springframework.boot:spring-boot-starter-data-mongodb")
```

  - Infrastructure: Kubernetes, Docker, SO, etc.
  - Mongock version: 4.1.18 & 4.3.8
  - How Mongock is implemented(builder or annotation approach, etc.): tried both, but ended up with builder.
  - How Mongock is imported: Part of the pom, or gradle, file regarding Mongock - pls see above
  - In general anything in your context that could be affecting
`application.yml`
```
spring:
  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
```
 - Steps
    - All the steps and actions you perform to reproduce the bug : no special steps, just run.

I think one possible way to fix would be honor the `spring.data.mongodb.field-naming-strategy`.

Thanks in advance!

(remastered regretfully with a polite and thankful tone)

**Comment by dieppa** [comment]
Sorry to hear you are experiencing that. It's not only the first user that reports this error, but also the first one that feels that way. We'll help you and assist you in anything we can, but you are not force to use Mongock. If you feel it doesn't work for you, you are free to use any other tool you think fits better our needs. 

Also because we are very responsive and we usually support developers very shortly, even for a paid tool, but for free. I understand your frustration but I would appreciate a bit more clam in your tone...we'll help you anyway 😉 


Please, can you provide your code? At least the way you are declaring your changeLogs and the Mongock bean?

Regards

**Comment by sam-element** [comment]
i know I've been a dick but thanks for your kindness.

**Comment by dieppa** [comment]
No problem, it's wise to rectify 😃 .

That's weird, as Mongock doesn't use spring data to access to their collections, it only supports it for the user. I am wondering if that it's related to some configuration in the database itself.

Anyway, we'll try to reproduce it. Although what you've provide is very useful and definitely needed, we also need:
- the way you are building your Mongock. If it's by properties, please provide the properties if it's via builder, please provide the code.
- Also your changeLogs. We don't need the actual business logic with the method's body empty. Just to see how you are creating them.


With that and all the information you have already provided, I think we will be able to reproduce it, if it's a Mongock's issue. But I still believe that it could be related to some configuration in your MongoDB. I would appreciate if you can load a docker container and run your applications agains it, just to discard it.

Regards

**Comment by sam-element** [comment]
Hi,

I tried to simplify my changelog as simple as it could get (empty body), but the error persists.
```
@ChangeLog(order = "001")
class InitialSetupMigration {

    @ChangeSet(order = "001", author = "initiator", id = "001-initCollectionNames")
    fun initCollectionNames(mongoTemplate: MongockTemplate) {

    }
}
```

in my application.yml, it's also as simple as it can get:
```
mongock:
   change-logs-scan-package: com.xxxx.config.dbinit
```

So I don't think it's related to the configs.

If I remove the naming strategy config,
```
spring:
   data:
     mongodb:
       field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
```
then everything starts working.

If I don't remove it, the field names in mongockChangeLog are like `execution_id`; if I remove it, the field names are like `executionId`, which matches the field names in the index to be created. So imho, honoring the naming strategy will fix the problem.

Thanks.

**Comment by dieppa** [comment]
Good morning,

We have tried to reproduce your error with the example project you can checkout [here](https://github.com/cloudyrock/mongock-examples/tree/version4/mongoDB/version4_x/spring5-springdata3), but everything works as expected.

Please can you perform the following steps:
- Checkout this [repository](https://github.com/cloudyrock/mongock-examples), branch `version4`. It's the default anyway
- Download and run the docker container `mongo-4.4.1`
- Run the project `spring5-springdata3` inside the repo
- **Check the created indexes**
- Now run it agains your MongoDB database
- And check the indexes

However, if by using the `spring.data.mongodb.field-naming-mapping-strategy` your issue is fixed, well, then it's fixed for you 😄

**Comment by sam-element** [comment]
Hi,

In my last comment, i said **removing** the `spring.data.mongodb.field-naming-mapping-strategy` makes things work. Adding it will break mongock index creation.

I just tried with your example repo. Same error happened. To recur it, please add the following to `application.yml` and see what will happen.

```
spring:
  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
```

Thanks.

**Comment by sam-element** [comment]
The point I've been trying to make is, when mongock creates the `mongockChangeLog` collection, the field/column naming honors the `field-naming-strategy` defined in config file. But when creating the index `{executionId, changeId, author}`, it doesn't honor the  `field-naming-strategy`. This results in that when `field-naming-strategy` is **snake case**, the `executionId` is named in **snake case** as `execution_id` in mongo collection, but the index creation still uses **camel case** `executionId` which doesn't exist (it has already been named as `execution_id` according to the strategy).

Possible solution:
When creating index for `mongockChangeLog`, instead of hardcoding `executionId` and `changeId` in camel case, check first the defined `field-naming-strategy` and accordingly update the `executionId` to the correct naming strategy.

Hope I made myself clear this time.

Thanks.

**Comment by dieppa** [comment]
aah ok, I was taking this totally the other way around. 

So, I see what you mean, we'll fix this, but I cannot commit to a date as we have a lot in our plates right now.
I see two solutions:
- While you wait for this(no less than a month), you can set indexCreation to false and create manually the index before hands
- Raise a PR with this in branch version4 and I will review. We'll take care of cherry pick this to the current develop branch where we are working on version 5.

Regards
