### ISSUE TITLE
Update maven-artifact and javassist dependencies to the latest

### ISSUE THREAD

**Issue by 20fps** [mongock/mongock#360]
We use mongock for mongodb migrations in our projects and use some automated vulnerabilities checks, had an issue with:
```
<dependency>
    <groupId>org.apache.maven</groupId>
    <artifactId>maven-artifact</artifactId>
    <version>${maven-artifact.version}</version>
</dependency>
<dependency>
    <groupId>org.javassist</groupId>
    <artifactId>javassist</artifactId>
    <version>${javassist.version}</version>
</dependency>
  ```
Current versions from mongock-runner-core 4.3.8: maven-artifact 3.6.1, javassist 3.18.2-GA.
So would be nice to have it updated from your side as well.
Also when do we expect new mongock release?

**Comment by dieppa** [comment]
Hello @20fps,

As you probably know those automated vulnerabilities are just warnings. More than recommended to be fixed, but don't represent anything serious. Also mention that mongock-core:4.3.8 is not using javassist(I am aware is still in the readme, but you can safely remove it). Regarding maven-artifact, we will be upgrading to 3.8.1, as recommended.

Regarding the new Mongock version, we are working on that. Initially we expected to have something for the end of June, but some unforeseen circumstances and the fact that we have identified some important features to be added as part of version 5, have forced us to delay a bit the release. Ideally(and this is not a commitment), the end of July is our target date to have at least a RC, maybe with some outstanding documentation to finalise.

**Comment by dieppa** [comment]
This has been fixed in latest versions :)
