### ISSUE TITLE
Is there any specific reason to not to use MongockSpring5 as a standalone?

### ISSUE THREAD

**Issue by thamidu** [mongock/mongock#366]
Hi,
First of all, I want to say thank you for this awesome project which made my life easy. While i was using this library, i came accross this issue where i was forced to use one of build methods in MongockSpring5, which are buildApplicationRunner and buildInitializingBeanRunner. 
In my use case, i need to run the migration on multiple databases. So i wanted to invoke execute method each time when i change the db name in MongoDatabaseFactory. In this case i was able to do that without any issue. But it also execute for once in beanInitialization/ applicaion startup. Here i tried different ways to disable that, but i could not. So i moved to standalonebuilder and now i dont get those additional features (DI, Profiling) which comes with Spring Builder.

So my question is, is there any specific reason(s) to not to allow an instance for manual execution?

Thanks. :)

**Comment by dieppa** [comment]
Sorry for the late reply.

First at all, just to let you know that, as part of the version 5, which we'll be releasing soon, we are delivering the multi-tenant feature which allows you to run a migration to multiple databases.

However, in the meantime, you can try these two approaches:
- Create a different named MongockInitializingBean for each database. This will delegate the execution to Spring. You need to provide the same parameters in the builders, except for the database. You can take a look to [this example](https://github.com/cloudyrock/mongock-examples/blob/598d90a829e172ed3d7131c2dedc62e5f8446932/mongoDB/version4_x/spring5-springdata3-builder/src/main/java/com/github/cloudyrock/mongock/Spring5SpringData3Builder.java#L38). Just change MongockApplicationRunner for MongockInitializingBean and provide a name to the bean. Do that for each database.

- Create as many ApplicationRunners  as databases you have and execute the `run(String... args)` manually.


Please note we recommend the first approach

**Comment by thamidu** [comment]
Thank you for the insight. 
In my case, i need to create beans dynamically. So guess i could create those beans using spring context at runtime. 

However I guess you missed my initial question. Apart from buildApplicationRunner and buildInitializingBeanRunne, Is there any reason to not to build a MongockSpring5 instance which should be executed manually? Just like a StandaloneRunner.

Sorry if I am bothering you.

**Comment by dieppa** [comment]
No worries, you don't bother us...as long as you use Mongock 😄 

I cannot really think an example where it's good idea to create a MongockSpring5 runner to run it manually. However, you can do it. As said, if you inject the bean(Mongock ApplicationRunner or Mongock InitializingBeanRunner), the execution is delegated to Spring, but if the runner is created, but not injected, you can runner manually. Yeah, you would be running manually a ApplicationRunner orInitializingBean, which doesn't makes too much sense, but well, it's possible and satisfies your needs.



Does that answer your question?...I am still not clear 😄
