### ISSUE TITLE
Helper to ease json file usage in changeset

### ISSUE THREAD

**Issue by Dreamwork57** [mongock/mongock#367]
Hi ! 
I started using Mongock just a week ago while searching for a Liquibase replacement on MongoDB / Spring Boot project, as I find the Liquibase support on NoSQL database quite poor. And so far, I kinda like the approche :)

Now one think that bothers me about ChangeSet is using Java code to build a BSON object and insert it in the database (as validator, data...). I'd like to use a JSON file inside a resources package instead of building it "as code", so I implemented my own abstract class inherited by all my ChangeLog files, that provides methods to read JSON file and convert it as BSON document (or document List for "insertMany" changesets) so it is easier for developers to import the initial data.

In my opinion, this could be a huge advantage to be added to Mongock if not already (if something similar already exists, I'll be very happy to use it instead of my "patch" :) ) for following reasons : 

- Eases the readability of imported data, as it would be directly JSON formatted in files
- Makes easier for developers to write their changesets, and less time consuming
- Makes possible to directly use MongoDB extracts to populate a database (could be useful for existing projects that want to step into using database management with Mongock)

I you think it could be useful, I can dig into the project to see possible ways to implement it :)

**Comment by dieppa** [comment]
hello, thanks. We have plans to add that as part of version 5(not in the initial release, but as an addition later), why don't raise  a pull request?

**Comment by Dreamwork57** [comment]
Nice ! Happy you got that in scope
I'll give it a look and raise a pull request then 👍

**Comment by dieppa** [comment]
Hello @Dreamwork57 , are you still keen on working on this? It would be great if you contribute :)

**Comment by dieppa** [comment]
Hello, as this issues is not moved, we will be closing it at the end of the week, unless you notify us you want to work on it 😃
