### ISSUE TITLE
cannot use different mongockChangeLog and mongockLock names

### ISSUE THREAD

**Issue by RiccardoManzan** [mongock/mongock#412]
Hi, i just approached this lib in a company project.
Is there any way to rename mongockChangeLog and mongockLock collections using standalone runner?

RN i'm using version 5.0.21.RC in a micronaut project (kotlin)

I already tried this way:

```kotlin
        MongockStandalone.builder()
            .setConfig(
                MongockConfiguration().apply {
                    migrationRepositoryName = "mongock_changelog"
                    lockRepositoryName = "mongock_locks"
                    migrationScanPackage = listOf("...")
                    setTransactionEnabled(false)
                }
            )
            .setDriver(MongoSync4Driver.withDefaultLock(client, databaseName))
            .buildRunner()
            .execute()
```

but those collections are still created with CamelCase and not snake_case as the rest of project collections.

**Comment by RiccardoManzan** [comment]
@dieppa thanks for your quick response!

**Comment by dieppa** [comment]
Hello @RiccardoManzan , can you try version 5.0.22.RC?

**Comment by RiccardoManzan** [comment]
I'm gonna check this RN.

**Comment by RiccardoManzan** [comment]
Unfortunately this is still not working, library still generates/refers to camel case collections.

**Comment by dieppa** [comment]
Ok, that was a RC it was released and I thought had that fixed. I will personally take a look later and update you

**Comment by RiccardoManzan** [comment]
I took a rapid look and i found this code fragment in `RunnerBuilderBase`:
```java
protected MongockRunner buildRunner(Operation operation, ConnectionDriver driver) {
  logger.info("Mongock runner {} version[{}]", getType(), getVersion());
  validateConfigurationAndInjections(driver);
  try {
    beforeBuildRunner();
    return new MongockRunnerImpl(
        buildExecutor(operation, driver),
        config.isThrowExceptionIfCannotObtainLock(),
        config.isEnabled(),
        eventPublisher);
  } catch (MongockException ex) {
    throw ex;
  } catch (Exception ex) {
    throw new MongockException(ex);
  }
}
```
I may be wrong as just take a rapid look and i don't know the whole project architecture, but it looks like collection names set in config are just ignored.
Maybe those fields can be safely removed? idk.

After looking at your fix commit, i discovered that those collection names are set among the driver, so i tried with this runner builder:

``` kotlin
MongockStandalone.builder()
    .addMigrationScanPackage("company.yoroi.migrations")
    .setTransactionEnabled(transactionEnabled)
    .setDriver(
        MongoSync4Driver.withDefaultLock(client, databaseName)
            .apply {
                this.setMigrationRepositoryName("mongock_changelog")
                this.setLockRepositoryName("mongock_locks")
            }
    )
    .buildRunner()
    .execute()
```
This way worked as intended.

**Comment by dieppa** [comment]
Hey @RiccardoManzan , I suggest to use that way you tested it works(I can confirm it does)

We will fix the config setter. It's worthy to mention that this bug is because the serConfig is not intended to be used in the builder, just by the Spring configuration, but there is nothing that tells you that, so you cannot guess.

Anyway, we'll fix that in the next version :)

Thanks

**Comment by dieppa** [comment]
fixed
