### ISSUE TITLE
@Configuration annotation on the MongockSpringConfiguration prevent to use spring-native

### ISSUE THREAD

**Issue by olivierboudet** [mongock/mongock#417]
When trying to use mongock in a spring-native application, the _useless_ `@Configuration` annotation on the `@ConfigurationProperties` `MongockSpringConfiguration` class confuses the aot engine and prevent to start the app.

**Comment by dieppa** [comment]
Hi @olivierboudet. I closed the PR as it should be agains `develop` branch. Once done it I will merge it and release it. Thanks!
