### ISSUE TITLE
Warning on console on @ChangeUnit execution

### ISSUE THREAD

**Issue by sfgvieira** [mongock/mongock#429]
**Describe the bug** 

When I start my app, if a changeunit has to be executed it will show in the console:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by javassist.util.proxy.SecurityActions (file:/home/vieira/.m2/repository/org/javassist/javassist/3.18.2-GA/javassist-3.18.2-GA.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of javassist.util.proxy.SecurityActions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**To Reproduce**

Steps and conditions to reproduce the behavior:
 - Conditions:
    - Springboot 2.5.7 with spring-boot-starter-data-mongodb, mongock-springboot and mongodb-springdata-v3-driver
    - Mongock 5.0.25
    - How Mongock is implemented: annotation approach
    - How Mongock is imported: Part of the pom
 - Steps
    - I just upgraded from 4.3.8 following the upgrade instructions

**Expected behavior**

No warning :)

**Comment by sfgvieira** [comment]
I decided to try to upgrade to spring boot 2.6 and noticed the warning went away. This is then fine for me :)

**Comment by dieppa** [comment]
Hello @sfgvieira ,

could you provide the following information?
- Which java version you are using
- a dependency tree of your projects**(*1)**

**(*1)**That warning you should states the javaassit version `3.18.x`, which Mongock was using in version 3 and produce that error. However we have moved to a most recently version, `3.28.0-GA`, which fixes that.

It seems your project is using the same library(maybe inderctly, brought transitively by another dependency), version 3.18.2.GA, which is causing the problem. With a dependency tree we can clarify that, exclude javassists form that library and lets Mongock to bring the version `3.28.0.GA`
