### ISSUE TITLE
Empty author causes problems with old changeLog when author is empty

### ISSUE THREAD

**Issue by oliverlockwood** [mongock/mongock#439]
**Describe the bug** 

If you have a deployed environment where migrations have already been run in MongoCK 4.x, with the `author` field set to an empty string then, upon upgrading to 5.x:
* a runtime exception `io.mongock.api.exception.MongockException: author cannot be null or empty` forces you to set a non-empty value for `author`
* once you set a non-empty value for `author`, then these migrations **which were already previously applied** get executed again.

**To Reproduce**

1. Define one or more migrations using MongoCK version 4.x, without the `author` field specified.
2. Run your app in a given environment.  The migrations get run.
3. Upgrade your app's dependencies to MongoCK version 5.x.  When you try and run it, you'll hit the runtime exception:
    ```
    io.mongock.api.exception.MongockException: author cannot be null or empty.
        at io.mongock.runner.core.internal.ChangeSetItem.<init>(ChangeSetItem.java:44)
    ```
4. Add an `author` value to the migration definitions.
5. Run the app again.  The previously-applied migrations get run again.

**Expected behavior**

In my view:
* It should be possible to configure the legacy `@com.github.cloudyrock.mongock.ChangeSet` annotation with an empty value for `author`.
* By all means, the new `@ChangeUnit` annotation introduced in MongoCK 5.x can disallow an empty `author` value.  After all, the notes at https://mongock.io/v5/from-version-4-to-5/#deprecations advise that "For existing changeLogs created prior version 5: Leave it untouched, keeping the deprecated annotation."

The problem is you can't follow the guidelines and leave them untouched, due to the strict runtime exception described!

**Comment by dieppa** [comment]
Thanks @oliverlockwood ,

we'll take a look and will keep you updated

**Comment by dieppa** [comment]
Hey @oliverlockwood ,

__we have released [Mongock 5.0.29](https://github.com/mongock/mongock/releases/tag/mongock-5.0.29) and this should be fixed. Please, give a try and let us know.__

Behaviour:
- Legacy `@ChangeLog` allows empty strings, but no null.
- `@ChangeUnit` also allows empty string at definition, but in that case, the default value is "default_author"
- There is an option to set a generic default author. Method `setDefaultMigrationAuthor(String)` in the builder or property `mongock.default-migration-author`

And one last thing, I highlight 
> For existing changeLogs created prior version 5: Leave it untouched, keeping the deprecated annotation.

Our philosophy is to treat the migrations as source of truth and should't be amended once released. 

I hope this help. Let us know if you have any question/issue and please close this issue if it's verified to work

**Comment by oliverlockwood** [comment]
The new version 5.0.29 works well for me.

Thanks for putting the fix out so promptly!

**Comment by dieppa** [comment]
Thank you for your feedback @oliverlockwood. Can I ask if you are using Mongock in professional project? And if so, could you provide some information such as industry, company name is possible.

And if you can follow our new [twitter account](https://twitter.com/MongockTeam), it would awesome

Thanks!

**Comment by oliverlockwood** [comment]
Sure @dieppa, no problem.  Yes indeed, we are using it in a professional project.

I work on the [Flex Media Platform](https://www.dalet.com/products/flex/) team at [Dalet](https://www.dalet.com).

Mongo is one of a number of backend data stores that we use to power Flex, and we rely on MongoCK for performing migrations in Mongo.

Hope that gives you all the info you need!

I'm afraid I'm a Luddite who doesn't use Twitter, so you won't find me following you any time soon 😄
