### ISSUE TITLE
Mongock cannot find classed/methods annotated on Spring Boot jar

### ISSUE THREAD

**Issue by infoShare** [mongock/mongock#472]
## Description

When starting migration from the spring boot *.jar file - migration classes are not found by Mongock.

## PRIORITY

MAJOR

### Mongock
- Mongock version: 5.0.25
- Modules involved - spring boot, mongodb
- How Mongock is used - MongockApplicationRunner

### Environment
- Spring Boot 2.6.1, spring-data-mongodb 3.3.0
- Local run from *.jar / Docker container

## Steps to Reproduce

1. Build spring-boot *.jar file with migration classes
2. Run *.jar locally (java -jar *.jar) or on docker container

## Behaviour

**Expected behavior:** Migration classes should be found + migration should be executed

**Actual behavior:** No migration classes found when started from *.jar

**How often the bug happens:** Always

## Additional context

It might be related with Spring Boot class loader.
When using *.war file instead of spring-boot *.jar file migration is working correctly.

**Comment by dieppa** [comment]
Hello @infoShare ,

mmm, it sounds weird. Can you provide the properties file you are using? So we can try to reproduce it

Btw, latest version is 5.0.32, I suggest to upgrade, anyway

**Comment by infoShare** [comment]
We're using only this piece of code for Mongock + all migration scripts are on MIGRATION_PATH package.

    @Bean
    public MongockApplicationRunner mongockApplicationRunner(ApplicationContext springContext, MongoTemplate mongoTemplate) {
        return MongockSpringboot.builder()
                .setDriver(createDriver(mongoTemplate)) // SpringDataMongoV3Driver.withLockStrategy(...)
                .addMigrationScanPackage(MIGRATION_PATH)
                .setEventPublisher(springContext)
                .setSpringContext(springContext)
                .buildApplicationRunner();
    }

+ spring-boot-maven-plugin is used.

**Comment by osantana85** [comment]
Hello @infoShare, we are checking it and tomorrow we'll let you know whatever.

**Comment by osantana85** [comment]
Hello again @infoShare, we have checked your issue with our example projects and it works fine. Could you please take a look to our [builder example](https://github.com/mongock/mongock-examples/tree/master/mongodb/springboot-builder) and check what differences they are?

**Comment by infoShare** [comment]
@osantana85, @dieppa It looks like it's a problem with newest reflections version.

        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
            <version>0.10.2</version>
        </dependency>

Please find example on my repository: https://github.com/infoShare/mongock-reflections.git
When running on IDE - migration is working correctly, when from *.jar - migration classes are not found.
When executing from *.war file - it's working fine (you can check it on branch "war")

**Comment by osantana85** [comment]
Hello @infoShare, I finally reproduced it, so you are right, there is a problem with that version... We'll work on it and let you know.

**Comment by osantana85** [comment]
Hello @infoShare,

Mongock is working with `reflections 0.10.1`. 

The problem seems to be due to the fact that  your project imports directly(or transitively) `reflections 0.10.2`, which has a bug in it. There is nothing to fix in our end.

To fix the issue in your project, we suggest:

1. run `mvn dependency:tree` 
2. identify which dependency imports `reflections 0.10.2`
3. Exclude it with
```java
        <dependency>
            <groupId>org.company</groupId>
            <artifactId>SOME-LIBRARY-IMPORTING-REFLECTIONS</artifactId>
            <version>1.0.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.reflections</groupId>
                    <artifactId>reflections</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

That should make Mongock import the version 0.10.1, if not you can add the dependency manually in your pom.

I hope it helps, regards

**Comment by infoShare** [comment]
So if there is nothing that can be done to use 0.10.2 without being affected by this bug - we need to wait for reflections fix. Thank you !

**Comment by dieppa** [comment]
@infoShare , there seems to be an option found y @osantana85 , but we are not sure we want to introduce a buggy version in our artifact, even with a theoretical workaround. 

Anyway, we are considering to do ourselves what reflections library is providing. We have had many issues related to this library.

**Comment by infoShare** [comment]
It's always better to do this I dependently. I was trying to find a workaround using Reflections constructor  with Configuration + additional filtering for packages but it wasn't very pretty.

**Comment by ahmadsab95** [comment]
The issue still reproduce  although there is no dependency import 0.10.2 ,
The only difference is  that I put the change unit classes in another module and add this module as dependency of the impl module

**Comment by dieppa** [comment]
@ahmadsab95, by module do you mean another jar? So if I use the [quick-start ](https://github.com/mongock/mongock-examples/tree/master/mongodb/springboot-quickstart) example project as template, create another jar which only stores the changeUnits and import it to the main project, I should be able to reproduce the issue, shouldn't I?

Which JDK version are you using?

**Comment by ahmadsab95** [comment]
@dieppa yes , its only reproduce when i run it from command java  - jar ... , when run it using IntelliJ its works fine 
JDK 11

**Comment by ahmadsab95** [comment]
@dieppa did you reproduce it ?

**Comment by dieppa** [comment]
Hello @ahmadsab95 , today is bank holidays in UK. We'll look at it in the next days.
Regards

**Comment by ahmadsab95** [comment]
Hello @dieppa , any update ? 
(I downgrade to version 4 and its not reproduce there)

**Comment by dieppa** [comment]
Sorry, we were looking for this issue(we knew there was something there but we weren't sure) and we didn't find it. Now I see it's closed.

I will tell you something late this evening

**Comment by osantana85** [comment]
Hello @ahmadsab95 , we tested it the way you described(with the changeUnits in an independent jar) using our example projects (Springboot and standalone variants) and we weren't able to reproduce it (JDK8 and JDK11).

Anyway,  are you using Springboot in your App? If not,  are you producing an uber jar somehow when compiling?

**Comment by ahmadsab95** [comment]
@osantana85 yes , 
When i am debugging the process when running from jar its can't find the clasess with the changeunit annotation

**Comment by dieppa** [comment]
@ahmadsab95 , sorry it wasn't clear 😄 

Are you using Springboot? Yes/no
Are you producing an uber jar? Yes/No

**Comment by ahmadsab95** [comment]
Yes i am using spring boot , 
No not using uber jar .

**Comment by dieppa** [comment]
Assuming you are building your app and the chageUnits project with JDK 11 and you are also running the application with JDK11, that's pretty weird. We have tested it all those cases and it works fine.

Let's do this. We are creating a branch on our example project with the scenario described, so you can pull it, run it, confirm it works and, if so, spot the differences between that and your project

**Comment by infoShare** [comment]
@ahmadsab95 This setup (spring boot + JDK11 + ChangeUnits on separate module used as mvn dependency) works fine in our case.

**Comment by dieppa** [comment]
@ahmadsab95, can you provide the dependency tree `mvn dependency:tree` so we can check which reflections version your project is actually importing?

**Comment by ahmadsab95** [comment]
@dieppa sorry I can't, but i run it and the only reflections version I found is 0.10.1.

**Comment by dieppa** [comment]
Hello, sorry, it has been some time. From our tests and other users, we can't reproduce the error and we highly believe is not relate toMongock itself. Without accessing to the code to debug it, we cannot really tell you more.

**Comment by brunoventurazup** [comment]
Hey guys, the issue still happening here. I saw on my maven dependency tree the reflections version and everything looks fine, as @ahmadsab95 case. 

To help debugging, i built a sample application and upload it on my [Github repository](https://github.com/brunoventurazup/mongo.abelha)

**Comment by dieppa** [comment]
Thanks @brunoventurazup ,

we'll use that repo to reproduce it

**Comment by brunoventurazup** [comment]
Hello, @dieppa!

I have found a workaround to this issue, the problem is on `Reflections v1.10.1`, so i forced a downgrade to `Reflections v0.9.11` on my application pom.xml. i did something like it:

```xml
        <!-- MongoCK - MongoDB Migration Tool -->
        <dependency>
            <groupId>io.mongock</groupId>
            <artifactId>mongock-springboot</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.reflections</groupId>
                    <artifactId>reflections</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.mongock</groupId>
            <artifactId>mongodb-springdata-v2-driver</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.reflections</groupId>
                    <artifactId>reflections</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
            <version>0.9.11</version>
        </dependency>
```

PS: I did it because there is an [open issue](https://github.com/ronmamo/reflections/issues/279) about it on Reflections Github repo.

**Comment by dieppa** [comment]
Hello, as this is an actual bug in the reflections library and there i a workaround provided by @brunoventurazup(**thanks!!**), this issue will be closed and we'll add it to the documentation

**Comment by ahmadsab95** [comment]
@dieppa - yes it works, Thanks. (Apologies for the delayed response)
