### ISSUE TITLE
Mongock multi tenant won't work

### ISSUE THREAD

**Issue by Helferon** [mongock/mongock#485]
## Description

Mongock multi tenant won't work

### Mongock
- Mongock version 5.0.34
- springboot
- Builder

### Environment
- Spring, Spring data, MongoDB driver

## Steps to Reproduce

MongockSpringboot.builder()
                .setDriver(
                        SpringDataMongoV3DriverProfessional.multiTenant()
                )

can not be compiled because 
Required type:
ConnectionDriver

Provided:
MultiTenantDriverImpl
<io.mongock.professional.driver.mongodb.springdata.v3.SpringDataMongoV3DriverProfessional>

**Comment by dieppa** [comment]
@Helferon, sorry, we have been busy with other stuff. was this fixed?

**Comment by Helferon** [comment]
Hi, thanks for replying, the problem was a conflict between the professional package and the original mongock dependency
