### ISSUE TITLE
Is it supported Spring Boot Reactive MondoDB driver?

### ISSUE THREAD

**Issue by Numichi** [mongock/mongock#489]

**Comment by dieppa** [comment]
You can get more information in this [link](https://github.com/mongock/mongock/discussions/484)

Summary, we will provide support for reactive MongoDB driver, but still this will work in a blocking way. Why then is useful the reactive support in Mongock? Just to avoid the need of importing the reactive and non reactive libraries and be able to use just one framework for both, main application and migration
