### ISSUE TITLE
Elasticsearch driver

### ISSUE THREAD

**Issue by dieppa** [mongock/mongock#492]
## Description
Mongock driver for elasticsearch

## Bounty 💰💰
£150 

## Instructions
- To claim this driver, please make a comment and we'll get back to you as soon as possible.
- Follow our [example project](https://github.com/mongock/mongock-driver-simpsonsdb) to understand the process. The readme file provides all the information you need, but if we miss anything, please, feel free to raise any question
 
## Features
- [ ] Transactional
- [x] Springboot support
- [x] Native(no sprin gdata nor framework) 
- [x] Springdata

## Modules required
- [x] mongock-driver-elasticsearch **(parent)**
- [x] elasticsearch-driver
- [x] elasticsearch-springboot-driver
- [x] elasticsearch-springdata
- [x] mongock-driver-elasticsearch-bom

**Comment by vijamesDD** [comment]
@dieppa , how come this has been closed? Has an ES driver been created? The Mongock documentation says its "coming soon" https://docs.mongock.io/v5/driver/index.html#drivers-available
Thanks!

**Comment by dieppa** [comment]
Hello @vijamesDD ,

we dismissed the Elasticsearch's driver because we are working on a new cloud based solution which will support all the databases(just to be clear, this doesn't mean your data would be stored in the cloud, just the Mongock's data).
