### ISSUE TITLE
Cassandra driver

### ISSUE THREAD

**Issue by dieppa** [mongock/mongock#493]
## Description
Mongock driver for cassandra

## Bounty 💰💰
£150 

## Instructions
- To claim this driver, please make a comment and we'll get back to you as soon as possible.
- Follow our [example project](https://github.com/mongock/mongock-driver-simpsonsdb) to understand the process. The readme file provides all the information you need, but if we miss anything, please, feel free to raise any question
 
## Features
- [ ] Transactional
- [x] Springboot support
- [x] Native(no spring data nor framework) 
- [x] Springdata

## Modules required
- [x] mongock-driver-cassandra **(parent)**
- [x] cassandra-driver
- [x] cassandra-springboot-driver
- [x] cassandra-springdata
- [x] mongock-driver-cassandra-bom

**Comment by crimsonvspurple** [comment]
This says closed as completed but I can't find anymore info on this. Is the current status publicly disclosable? Thank you.
