### ISSUE TITLE
Required to provide scan packages

### ISSUE THREAD

**Issue by fkrauthan** [mongock/mongock#500]
## Description

It seems like that I have to provide at least one scan package for mongock to work. But in my case I don't want to use package scanning and instead just provide a list of migrations via `addChangeLogClasses`. Is there any way to disable that validation or am I doing something wrong?

## PRIORITY

NORMAL

### Mongock
- Mongock version: 5.0.35
- Modules involved: Standalone
- How Mongock is used: Builder

### Environment
- Ktor 2.0
- MacOS M1

## Steps to Reproduce

1. Create a mongock instance ```        val mongoClient = MongoClients.create(createClientSettings(config));
        return MongockStandalone.builder()
            .setDriver(MongoSync4Driver.withDefaultLock(mongoClient, config.database))
            .addMigrationClasses(config.migrations)
            .addMigrationScanPackages(emptyList())
            .buildRunner()```
2. Run the code

## Behaviour

**Expected behavior:** Not throwing any errors and only execute the provided list of migration classes

**Actual behavior:** Throws error: `Scan package for changeLogs is not set: use appropriate setter`

**How often the bug happens:** Everytime

**Comment by dieppa** [comment]
Hello @fkrauthan ,

yeah, the changeUnits location is required. Initially it was set by the scan packager, but later it also accepts classes directly. It's probably a minor bug. 

For the time being, until we fix it,  **just pass and dummy String as package**. It won't find anything there, but it should complain neither.
