### ISSUE TITLE
Add new runner-type for Spring

### ISSUE THREAD

**Issue by rloeffel** [mongock/mongock#507]
## Description
The runner type InitializationBean runs too early in certain szenarios. In our case for example we need to startup Kafka and there are some beans that runs in a postprocessing phase. In Spring there is also the possiblity to define a Bean that runs just right after initialization but before the application context is started.

I did a quick implementation in our local repository and it works as expected. here is our code:

public class MongockLifecycleRunner extends MongockRunnerBase implements SmartLifecycle {

  private boolean isRunning;
  private int phase;

  protected MongockLifecycleRunner(MigrationExecutor executor,
                                   ChangeLogService changeLogService,
                                   boolean throwExceptionIfCannotObtainLock,
                                   boolean enabled,
                                   SpringEventPublisher eventPublisher, int phase) {
    super(executor, changeLogService, throwExceptionIfCannotObtainLock, enabled, eventPublisher);
    this.phase = phase;
  }

  @Override
  public void start() {
    this.execute();
    this.isRunning = true;
  }

  @Override
  public void stop() {
    this.isRunning = false;
  }

  @Override
  public boolean isRunning() {
    return isRunning;
  }

  @Override
  public int getPhase() {
    return phase; 
  }
}

can you add this to your repo?

**Comment by dieppa** [comment]
Hello @rloeffel ,

that sounds like a good suggestion. Why not raising a pull request yourself?

**Comment by dieppa** [comment]
@rloeffel 

what classes are you referring to?

**Comment by dieppa** [comment]
I think this can help:
- In [this folder](https://github.com/mongock/mongock/tree/develop/mongock-core/mongock-runner/spring/springboot/mongock-springboot-base/src/main/java/io/mongock/runner/springboot/base) you can see the two Springboot runners, `MongockInitializingBeanRunner` and `MongockApplicationRunner`

- [This](https://github.com/mongock/mongock/blob/develop/mongock-core/mongock-runner/spring/springboot/mongock-springboot-base/src/main/java/io/mongock/runner/springboot/base/config/SpringRunnerType.java) is the enum with the types 

- [This](https://github.com/mongock/mongock/blob/develop/mongock-core/mongock-runner/spring/springboot/mongock-springboot-base/src/main/java/io/mongock/runner/springboot/base/builder/SpringApplicationBean.java) it's the interface that the builder implements to have the methods that produce(on demand) the different Springboot runners. You need to add another method returning the new one

- And once that is done, although the class won\t complain as it's abstract, you should implement the method  [here](https://github.com/mongock/mongock/blob/develop/mongock-core/mongock-runner/spring/springboot/mongock-springboot-base/src/main/java/io/mongock/runner/springboot/base/builder/SpringbootBuilderBase.java) in lines 106-112 you see how easy it is 😉 


let e know if you need anything else

**Comment by dieppa** [comment]
@rloeffel is this still relevant?

**Comment by rloeffel** [comment]
actually yes, but I had no time so far to give it a try...

**Comment by dieppa** [comment]
Hello @rloeffel,

thanks for your answer. Not sure what does that mean? Are you going to give a try or we better close this issue and you open it if/when you have some time?

**Comment by dieppa** [comment]
Hello @rloeffel ,

as I see this hasn't moved since my last message, I think we better close and ask for re-open it if you feel it still relevant. Thanks
