### ISSUE TITLE
Validation should check ChangeUnits have constructor

### ISSUE THREAD

**Issue by msmerc** [mongock/mongock#508]
## Description

`ChangeLogRuntimeImpl` assumes that a `@ChangeUnit` has constructors and that the first constructor is the one it should use.

If this is the case then the 

## PRIORITY

Minor

### Mongock
- Mongock version 5.0.35 standalone

## Steps to Reproduce

Here's my ChangeUnit
```java
    @ChangeUnit(id="mongock 5", order = "23")
    static class Mogock5Migration {
        @Execution
        public void migrationMethod() {
            LOGGER.info("Performing a no-up upgrade");
        }
        @RollbackExecution
        public void noRollback(){}
    }
```

Arguably this is a pointless changeUnit! But it's not obviously invalid.

## Behaviour

**Expected behavior:** [What you expect to happen]

I'd expect `AnnotationProcessor.validateChangeUnit()` to give some helpful error about there needing to be a constructor.

**Actual behavior:** [What actually happens]

Arrayindex out of bounds exception

**Comment by msmerc** [comment]
If there are multiple constructors that might also cause weird behaviour. Perhaps the validator should guard against that too?

**Comment by msmerc** [comment]
And since I'm here :p: 

The exception:
`io.mongock.api.exception.MongockException: ChangeUnit[com.....DatabaseChangelog$Mogock5Migration] must have only one RollbackExecution method`

Is a bit misleading since it implies I have several when in fact I've got none. Could the language be improved? Maybe to "must have exactly one..." - or for another line of code it could say "is missing" vs "has more than one"?

**Comment by dieppa** [comment]
Hello @msmerc , as you pointed this priority ir minor, but you are welcome to raise a PR!

**Comment by thekaleidoscope** [comment]
Hello @dieppa , I had a look at the codebase and wanted to confirm a few things,

1. We only want to allow exactly one constructor in the `@ChangeUnit` class
2. The constructor must have at least one parameter satisfies `Class.isAssignableFrom` MongoOperation or MongoRepository
3. The validation could be done in the process of `ChangeLogService.buildChangeLogInstance`specifically in `annotationProcessor.validateChangeUnit`

Can please confirm/comment on the above? And also, can you please let me know if someone is already working on this and the change is still relevant.

**Comment by dieppa** [comment]
Hello @msmerc 

The error you got `Arrayindex out of bounds exception` is probably related to the fact that Mongock takes the first constructor(`type.getConstructors()[0]`). Even for classes for which you don't explicitly provide a constructor, the empty constructor is provided by default, so this shouldn't be a problem. The only way I can think this could happen if Mongock cannot access to the changeUnit's constructor, for example if it's private.

Regarding your questions.

1. Currently Mongock allows multiple constructor, it won't break, but it's not guaranteed which one of them it will take and . We want to add an annotation to tell Mongock which constructor to take, while you can use the other for other purpose like testing
2. As mentioned in point(1) we want to allow multiple constructor, but telling Mongock which one it should take, rather than not allowing multiple constructor.

We are happy to assist you if you want to raise a PR for this(allow multiple constructor, while allowing to indicate to Mongock which to take). This should be relatively easy

1. Create an annotations in package `io.mongock.api.annotations` to communicate Mongock the constructor to take. It could be called '@ChangeUnitConstructor' or something like that
2. In the class `ChangeLogRuntimeImpl`, method `getConstructor`, implement the logic to take the constructor annotated with the previous annotation or the first one(current implementation) otherwise
3. Add some test to validate it

Let us know if you want to proceed with this and I will personally assist you on this 😃

**Comment by thekaleidoscope** [comment]
Hello @dieppa, I know didn't tag me, so not sure If you were talking to me for the changes, If you were, I'd be glad to have a stab at this.

on 
> the empty constructor is provided by default

This is just the no arg constructor created by default for a class right, but even if this exists, there wouldn't be any mongoTemplate injected, so not sure how a mongock migration can exist without it. Anyway, I guess we can leave that to the discretion of dev.

Also, we should add validation to ensure exactly one constructor is annotated with `ChangeUnitConstructor` or something right?

**Comment by msmerc** [comment]
@dieppa Do you think multiple constructors is a realistic use case? It's probably easier to have the validator generate an error if there are multiple or zero constructors - after all, only one can be invoked in practice. 

Why make this any more complex?

**Comment by dieppa** [comment]
@msmerc, while in production only make sense one constructor and that should be good, you may want to have more than one for testing purpose. 

I believe that's not really important, but a nice to have. So you can have these scenarios
- Only one constructor(no annotation)
- More than one constructor(only one of them with annotation)
- More than one constructor(with no annotation) -> Exception

**Comment by thekaleidoscope** [comment]
I'm summarizing the acceptance criteria that I understood:
1. Existing ChangeUnits should run without any exception but with a warning `Mark at least one public constructor in the @ChangeUnit <ChangeUnitName> with @ChangeUnitConstructor denoting it's dependecies are to be injected, This will be mandatory with Mongock version 6`
2. New ChangeUnit with no constructor (public and private) should also run without exception but with above warning
3. New ChangeUnit with more than one public constructor without `@ChangeUnitConstructor` should also run without exception but with above warning
3. ChangeUnit without any public constructor but with one or more private constructors should end with exception of message `No public constructors exist for dependency injection, Please provide at least one public constructor with @ChangeUnitConstructor`
4. ChangeUnit with at least one public constructor and with exactly one constructor having `@ChangeUnitConstructor` should execute without any exception or warning
5. ChangeUnit with at least one public constructor and with more than one constructor having `@ChangeUnitConstructor` should execute without any exception `@ChangeUnitConstructor should be marked exactly once in a ChangeUnit`

please let me know if this looks okay @dieppa @msmerc

**Comment by msmerc** [comment]
@thekaleidoscope - I think you're not being strict enough. @dieppa summarasied it neatly:

These are ok:
* Only one constructor provided(no annotation)
* More than one constructor provided (only one of them with annotation)

This generates an error:
* No constructor provided
* More than one constructor provided (multiple have annotation)

This generates a warning:
* More than one constructor provided (none are annotated)

By "constructor" here, we specifically mean "a valid constructor that Mongock can inject dependencies into". So private constructors, constructors with uncomprehendable / uninjectable arguments, constructors with no arguments (including default constructors) simply do not count as "constructors" for the above checks. We shouldn't care if these constructors are present on the objects - but we should word the messages careful to indicate what we are doing, so instead of saying (say) "class has no constructors", say something like "could not find a constuctor that Mongock and use for dependency injection" or something like that.


Disclaimer - I'm only a Mongock user, so this is simply what I'd like to see. @dieppa  is a project member so what he says goes!

**Comment by dieppa** [comment]
@thekaleidoscope , I will take a look this evening 😉

**Comment by thekaleidoscope** [comment]
@msmerc, dieppa did say we don't want to break what already works for version 5, Hence all the warning scenario in version 5, would become error in version 6. This includes the `No constructor provided` scenario. Not sure which else scenario you think I'm being too leniant on.

Agree with the change of wordings,
Suggestions:

Warning for scenario 1, 2, 3: `Mark one constructor in the @ChangeUnit <ChangeUnitName> with @ChangeUnitConstructor for mongock to use for dependency injection, This will be mandatory with Mongock version 6`

Exception in scenario 4: `Could not find a constructor that Mongock can use for dependency injection, Mark one constructor in the @ChangeUnit <ChangeUnitName> with @ChangeUnitConstructor`

Exception in scenario 6: `Expected exactly one constructor to be marked with @ChangeUnitConstructor in @ChangeUnit <ChangeUnitName> , but found <number of constructors with annotation @ChangeUnitConstructor>`
