### ISSUE TITLE
Error during creating connectionDriver

### ISSUE THREAD

**Issue by fkopriva** [mongock/mongock#517]
hi guys, I updated mongock to version 5.0.36, using springboot 2.5.2, java 11 and mongodb-springdata-v3-driver and
this is my yml config: 
```mongock:
  migration-scan-package:
    - com.bosch.migrations
  runner-type: applicationrunner
  mongo-db:
    write-concern:
      w: majority
      w-timeout-ms: 1000
      journal: true
    read-concern: majority
    read-preference: primary
```

Whenever I start my integration tests, I got exception
`Factory method 'connectionDriver' threw exception; nested exception is com.mongodb.MongoCommandException: Command failed with error 2 (BadValue): 'cannot use 'j' option when a host does not have journaling enabled'`

This is my test config class
``` 
@Configuration
@PropertySource(value = "classpath:test.properties")
@ComponentScan(basePackages = {"com.bosch"})
@EnableAutoConfiguration
@Profile("test")
public class TestConfiguration extends AbstractMongoClientConfiguration {

    private static final String MONGO_DB_URL = "127.0.0.1";

    @Autowired
    private Environment env;

    @Autowired
    private MongodConfig mongoConfig;

    @Bean
    @Primary
    public CurrentUserService currentUserService() {
        // you have to mock the current user method in your test cases!
        return Mockito.mock(CurrentUserService.class);
    }

    @NotNull
    @Override
    protected MongoClientSettings mongoClientSettings() {
        return MongoClientSettings.builder()
                .applyConnectionString(new ConnectionString(
                        String.format("mongodb://%s:%s", mongoConfig.net().getBindIp(), mongoConfig.net().getPort())))
                .retryWrites(true)
                .build();
    }

    @NotNull
    @Override
    @Bean
    public MongoClient mongoClient() {
        final MongoClientSettings settings = MongoClientSettings.builder()
                .applyConnectionString(new ConnectionString(
                        String.format("mongodb://%s:%s", mongoConfig.net().getBindIp(), mongoConfig.net().getPort())))
                .retryWrites(true)
                .build();
        return MongoClients.create(settings);
    }

    @Bean
    @Primary
    public MongoTemplate mongoTemplate(MongoClient mongoClient) {
        return new MongoTemplate(mongoClient, "embeded_db");
    }

    @Bean
    @Primary
    public ObjectMapper objectMapper() {
        return new ObjectMapper();
    }

    @Bean
    @Primary
    public Jackson2ObjectMapperBuilder jackson2ObjectMapperBuilder() {
        return new Jackson2ObjectMapperBuilder();
    }

    @NotNull
    @Override
    protected String getDatabaseName() {
        return env.getRequiredProperty("mongo.db.name");
    }
```
Sometimes I got this 
` No qualifying bean of type 'io.mongock.driver.api.driver.ConnectionDriver' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}`
but when I inject ConnectionDriver to my config class it threw same error as I described before

Any idea what I did wrong or if I am missing something?

**Comment by dieppa** [comment]
Which MongoDB are you using for your integration test? In memory?

**Comment by fkopriva** [comment]
I am using flapdoodle embed mongo 3.4.3

**Comment by dieppa** [comment]
ok, that's what I wanted to read. 

**Short answer:** In testing you need to disable `mongock.mongo-db.journal`. This is done by setting it to false or simple remove it from the configuration

**Explanation**
flapdoodle is a in-memory database for MongoDB and you are forcing journaling by configuration with `mongock.mongo-db.journal=true`, which means you are telling MongoDB(flapdoodle) to acknowledge a write by writing in the file system, but it's not enable as it's in memory.

**Comment by fkopriva** [comment]
and default setting is also journal=true? because I didn't have it before and I got same error :D

**Comment by dieppa** [comment]
@fkopriva now you mention it, yes. the reason why is that Mongock requires a consistent process, that means that it wants to have the writes/reads committed before moving to the next changeUnit. The way to do that is by the configuration you showed in your first comment:
```yaml
  mongo-db:
    write-concern:
      w: majority
      journal: true
    read-concern: majority
    read-preference: primary
```

**Comment by fkopriva** [comment]
Thanks. Problem solved.

My current setting:
```
mongock:
  migration-scan-package:
    - com.bosch.migrations
  runner-type: applicationrunner
  mongo-db:
    write-concern:
      journal: false
```

**Comment by dieppa** [comment]
Great! Anyway, remember we only recommend that in test environments ;)
