### ISSUE TITLE
Migration skipped after start of application in openshift

### ISSUE THREAD

**Issue by fkopriva** [mongock/mongock#522]
Hello guys, 

hopefully last issue :)

I updated to mongock 5 and change configuration to this in openshift: 
```
    mongock:
      migration-scan-package:
        - com.bosch.migrations
      runner-type: applicationrunner
      enabled: true
      throw-exception-if-cannot-obtain-lock: true
      transaction-enabled: false
      mongo-db:
        write-concern:
          w: majority
          w-timeout-ms: 1000
          journal: true
        read-concern: majority
        read-preference: primary
```
and everything is running, tests are also running if I change journal to false. However 1 thing is not working. My migrations are always skipped -
```
[2022-03-15 10:34:01.421]  INFO [main] --- c.b.Application$Companion: Started Application.Companion in 55.115 seconds (JVM running for 59.873)
[2022-03-15 10:34:01.511]  INFO [main] --- i.m.r.c.e.o.c.MigrationExecutorBase: Mongock skipping the data migration. All change set items are already executed or there is no change set item.
[2022-03-15 10:34:01.511]  INFO [main] --- i.m.d.c.l.LockManagerDefault: Mongock releasing the lock
[2022-03-15 10:34:01.511]  INFO [main] --- i.m.d.c.l.LockManagerDefault: Mongock releasing the lock
[2022-03-15 10:34:01.612]  INFO [main] --- i.m.d.c.l.LockManagerDefault: Mongock released the lock
[2022-03-15 10:34:01.612]  INFO [main] --- i.m.r.c.e.o.c.MigrationExecutorBase: Mongock has finished
```

I created empty DB for that and it's still empty. Changelog collection is also empty. 
I tried to change the ChangeLog and ChangeSet to ChangeUnit and it's skipped too.
Do I have something wrong in the configuration?

Edit1: Migration are running properly on local env.

**Comment by dieppa** [comment]
Hello, first at all, no worries about raising issues, we'll try to help as much as we can

The only thing I can think  of it's that it's not finding anything in the package `migration-scan-package`. We are releasing a new minor version soon, probably today. We'll add a warning if no change units are found. I think  that can help.

Anyway, is that package `com.bosch.migrations` within your app or it's a module you are importing?

**Comment by fkopriva** [comment]
yea, it's folder where the migrations are stored. backend -> com -> bosch-> migrations - migration1, migration2, etc.

**Comment by dieppa** [comment]
which jdk are you using?

**Comment by fkopriva** [comment]
jdk 11, mongock 5.0.36

**Comment by dieppa** [comment]
Can you take a look to [this issue](https://github.com/mongock/mongock/issues/472), I think is related

**Comment by dieppa** [comment]
Hello @ifsantana , can you take a look to [the link posted previously](https://github.com/mongock/mongock/issues/472) and let us know if related. Cheers

**Comment by dieppa** [comment]
Hello @ifsantana  and @fkopriva , can you tell me if that issue was helpful so we can close this?

Thanks

**Comment by fkopriva** [comment]
Yea it seems it's related, but I am facing new problem - how to handle the exclusion in gradle.. I had also one more idea that I can downgrade version of mongo to old one which is not using that reflection package version.. Do you know when it was added? @dieppa

**Comment by fkopriva** [comment]
solved by workaround in mentioned issue

**Comment by ifsantana** [comment]
> Hello @ifsantana and @fkopriva , can you tell me if that issue was helpful so we can close this?
> 
> Thanks

Yeah! The workaround work here as well! Thanks @dieppa
