### ISSUE TITLE
Transaction isn't working on Standalone version 5.0.36  

### ISSUE THREAD

**Issue by miriambron** [mongock/mongock#545]
## Description

I'm trying to run a change UNIT as a transaction , I set transaction enabled both on the 
```MongockStandalone.builder().setTransactionEnabled(true)```
and both on ChengeUnit 
```@ChangeUnit(id = "update", order = "0", transactional = true, runAlways = false)```

however , also when I have failure , I see that database status is partial migrated, the values committed to the database . 

My Builder looks like :

```
MongoClient client = getMainMongoClient();
		return MongockStandalone.builder()
				.setTransactionEnabled(true)
				.setDriver( MongoSync4Driver.withDefaultLock(client, MONGODB_MAIN_DB_NAME))
				.addMigrationScanPackage("com.local.mongock.changelogs")
				.setMigrationStartedListener(MongockEventListener::onStart)
				.setMigrationSuccessListener(MongockEventListener::onSuccess)
				.setMigrationFailureListener(MongockEventListener::onFail)
				.addDependency("mongoDB",client.getDatabase(MONGODB_MAIN_DB_NAME))
				.setTrackIgnored(false);

```

My update operation inside the changeunit looks like :

```collection.replaceOne(Filters.eq("_id", obj.get("_id")), obj);```

I tried to find a way to pass the mongock ClientCession into the ```replaceOne``` but didn't find a way to do it

## PRIORITY

CRITICAL

### Mongock
- Mongock version :5.0.36
- Modules involved: standalone, MongoDB 
- How Mongock is used : Builder execution

**Comment by osantana85** [comment]
Hello @miriambron , we have some examples where we use ClientSession. Please take a look at this [ClientInitializerChangeLog.java](https://github.com/mongock/mongock-examples/blob/master/mongodb/standalone-mongodb-sync/src/main/java/io/mongock/examples/changelogs/client/initializer/ClientInitializerChangeLog.java) and let us know if it works for you. Thanks

**Comment by miriambron** [comment]
> Hello @miriambron , we have some examples where we use ClientSession. Please take a look at this [ClientInitializerChangeLog.java](https://github.com/mongock/mongock-examples/blob/master/mongodb/standalone-mongodb-sync/src/main/java/io/mongock/examples/changelogs/client/initializer/ClientInitializerChangeLog.java) and let us know if it works for you. Thanks

Hello @osantana85 , thanks for your answer. 
 it really doesn't help
That means that I have to create the transaction myself, inject the session, and close the transaction? and if I want a separate  transaction for each step , I need to create the transaction in each execution inside the step code? 

Does that mean that in the stand-alone deployment you actually don't really support transactions, but only in the spring one? I's not reflected in the documentation.

**Comment by miriambron** [comment]
> Hello @miriambron , we have some examples where we use ClientSession. Please take a look at this [ClientInitializerChangeLog.java](https://github.com/mongock/mongock-examples/blob/master/mongodb/standalone-mongodb-sync/src/main/java/io/mongock/examples/changelogs/client/initializer/ClientInitializerChangeLog.java) and let us know if it works for you. Thanks

yes, it helped , Thanka!
