### ISSUE TITLE
CI Test Job should be guarding the master branch

### ISSUE THREAD

**Issue by thekaleidoscope** [mongock/mongock#547]
## Description

Currently, shouldThrowException_whenAuthorIsEmpty_IfChangeUnit test fails for code in master.
```
org.junit.ComparisonFailure: 
Expected :author cannot be null or empty.
Actual   :changeUnit[io.mongock.runner.core.changelogs.with_author_empty.ChangeUnitWithAuthorEmpty] author cannot be null or empty.
```

## PRIORITY

NORMAL

### Mongock
- Mongock version N/A
- Modules involved(springboot, standalone, MongoDB, DynamoDB, etc.) N/A
- How Mongock is used(builder or annotation approach, etc.) N/A

## Behaviour

**Expected behavior:** Tests to run when an MR is created to deploy branch of this repo

**Actual behavior:** No tests are run

**How often the bug happens:** N/A

**Comment by dieppa** [comment]
Can you check on `develop` branch. It's the branch should be working on 😉

**Comment by thekaleidoscope** [comment]
Yes, I'm working on deploy branch only, but just saw that code in master has some tests failures and since it was not caught earlier, thought of adding this issue
