### ISSUE TITLE
Scanning by package does not work when using the latest version of org.reflections library & runnable jar

### ISSUE THREAD

**Issue by jangatt** [mongock/mongock#554]
## Description

Scanning by package does not work when using the latest version of org.reflections library (0.10.2) when the application is packaged as a runnable jar. Basically any class annotated with ChangeUnit is not being picked up by the mongock libraries. 

The code has to be slightly updated to use a proper package scanner in the Reflection constructor. Example: 

```
new Reflections(new ConfigurationBuilder()
                .setScanners(Scanners.TypesAnnotated)
                .setUrls(ClasspathHelper.forPackage(package here)))
                .getTypesAnnotatedWith(ChangeUnit.class)
                .stream())
```

## PRIORITY

[CRITICAL]

### Mongock
- Mongock v 5.0.35
- org.reflections v 0.10.2

### Environment
- Runnable JAR File /Docker image

## Steps to Reproduce

1. Annotate a class with ChangeUnit
2. Make sure you are using the latest reflections library 
3. Build runnable jar and run
4. No migration classes are detected

## Behaviour

**Expected behavior:** Should pick up all classes annotated with ChangeUnit
**Actual behavior:** No classes are picked up by the reflections library

**How often the bug happens:** Always

## Link to repository using Mongock

https://github.com/mongock/mongock/blob/8523b9d813c9e251cc78e098eeaa768e323699e5/mongock-core/mongock-runner/mongock-runner-core/src/main/java/io/mongock/runner/core/executor/changelog/ChangeLogServiceBase.java#L152

**Comment by jangatt** [comment]
> 
Yes it seems the same issue - thanks!

**Comment by osantana85** [comment]
Ok @jangatt , so in order to close this issue, could you try that workaround and confirm us if it works for you? Thanks in advance.
