### ISSUE TITLE
Downgrade of Mockito Core Dependency while upgrading the bom version

### ISSUE THREAD

**Issue by pedrorlmarques** [mongock/mongock#559]
## Description
- Using the version io.mongock:mongock-bom:5.1.0 this will import the mockito-core version 4.5.1.
- While upgrading the bom version to 5.1.2 the mockito-core version is downgraded to version 3.2.4.

## PRIORITY
NORMAL

## Version and environment
- io.mongock:mongock-bom:5.1.0
-  io.mongock:mongock-bom:5.1.2

## Behaviour

**Expected behavior:** While upgrading the bom version the version of the mockito-core isn't supposed to be downgraded

**Actual behavior:** While upgrading the bom version the version of the mockito-core is supposed to be upgraded or stayed the same version

**Comment by dieppa** [comment]
Hello @pedrorlmarques , it seems that the dev team made a mistake related to the dependency management in the pom files. We are working to fix tat as soon as possile.

**Comment by dieppa** [comment]
Hello @pedrorlmarques , we have released the version 5.1.3. I believe that solves the issue you are experiencing. Please, give a try and let us know 😃
