### ISSUE TITLE
Index for Set<String> field is not being created

### ISSUE THREAD

**Issue by ArthurHarkivsky** [mongock/mongock#578]
## Description

[Description of the issue]

## PRIORITY

[NORMAL]

### Mongock
- Mongock version - 4.3.8

### Environment
- Spring boot 2.6.7, Docker, mongo from testcontainers - 1.17.2.

## Steps to Reproduce
This is being executed without errors.
```
@Configuration
public class MongoConfig {
    @Bean
    MongoTransactionManager transactionManager(MongoDatabaseFactory dbFactory) {
        return new MongoTransactionManager(dbFactory);
    }
}

@Component
@ChangeLog(order = "001")
public class Changelog001 {
    @ChangeSet(id = "create-photos-index", author = "Arthur Harkivsky", order = "001")
    public void migrateData(final MongockTemplate template) {
        log.info("Changelog 001 was started.");
        template
                .indexOps(X.class)
                .ensureIndex(new Index()
                        .on("photos", Sort.Direction.ASC));
        log.info("Changelog 001 is finished.");
    }
}

@Document(collection = "X")
public class X {
   private String idl
   private Set<String> photos;
}
```
but the result is
`docker-rs:PRIMARY> db.VehicleAggregate.getIndexes()
[ ]`

**Comment by ArthurHarkivsky** [comment]
it is, wrong replacement. Does not work for VehicleAggregate

**Comment by dieppa** [comment]
I suggest to upgrade to Mongock version 5.X and use Spring MongoTemplate directly, instead of **MongockTemplate**. It should work just fine.

You can see [this example](https://github.com/mongock/mongock-examples/tree/master/mongodb/springboot-quickstart) that uses Mongock 5.x

If, for any reason, you can, we'll take a look, but it will take longer as we prioritise version 5's issues.

**Comment by ArthurHarkivsky** [comment]
`io.mongock.api.exception.MongockException: Error in method[CreatePhotosIndexChangeUnit.execution] : Command failed with error 251 (NoSuchTransaction): 'Transaction 1 has been aborted.' on server localhost:62392. The full response is {"errorLabels": ["TransientTransactionError"], "ok": 0.0, "errmsg": "Transaction 1 has been aborted.", "code": 251, "codeName": "NoSuchTransaction", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1664570189, "i": 2}}, "signature": {"hash": {"$binary": {"base64": "AAAAAAAAAAAAAAAAAAAAAAAAAAA=", "subType": "00"}}, "keyId": 0}}, "operationTime": {"$timestamp": {"t": 1664570189, "i": 2}}}; nested exception is com.mongodb.MongoCommandException: Command failed with error 251 (NoSuchTransaction): 'Transaction 1 has been aborted.' on server localhost:62392. The full response is {"errorLabels": ["TransientTransactionError"], "ok": 0.0, "errmsg": "Transaction 1 has been aborted.", "code": 251, "codeName": "NoSuchTransaction", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1664570189, "i": 2}}, "signature": {"hash": {"$binary": {"base64": "AAAAAAAAAAAAAAAAAAAAAAAAAAA=", "subType": "00"}}, "keyId": 0}}, "operationTime": {"$timestamp": {"t": 1664570189, "i": 2}}}`

`mongock.transactionEnabled=true
mongock.migration-scan-package=com.transportexchangegroup.changelog`

`@Component
@ChangeUnit(id = "create-photos-index", author = "Arthur Harkivsky", order = "001")
public class CreatePhotosIndexChangeUnit {
    @Execution
    public void execution(final MongoTemplate template) {
        log.info("ChangeUnit 001 was started.");
        template.indexOps(VehicleAggregate.class)
                .ensureIndex(new Index()
                        .named("photosIndex")
                        .on("photos", Sort.Direction.ASC));
        log.info("ChangeUnit 001 is finished.");
    }

    @RollbackExecution
    public void rollbackExecution(final MongoTemplate template) {
        log.info("ChangeUnit 001 rollback was started.");
        template.indexOps(VehicleAggregate.class)
                .dropIndex("photosIndex");
        log.info("ChangeUnit rollback 001 is finished.");
    }
}`

**Comment by ArthurHarkivsky** [comment]
```
    private static void startAndInitializeMongoDBTestContainer() {
        try {
            if (mongo != null) {
                mongo.stop();
            }

            MongoDBContainer mongo = new MongoDBContainer(DockerImageName.parse("public.ecr.aws/docker/library/mongo:5.0.7")
.asCompatibleSubstituteFor("mongo"));
            mongo.start();
            System.setProperty("spring.data.mongodb.host", mongo.getHost());
            System.setProperty("spring.data.mongodb.port", "" + mongo.getMappedPort(27017));
        } catch (Exception var1) {
            log.error("Unable to stop/start mongoDBContainer.", var1);
        }

    }
```

**Comment by dieppa** [comment]
Nice!!

This is happening because you are trying to create the index inside a transaction(`@Execution` is executed inside a transaction) and MongoDB doesn't allow that.

We are working on a feature to be able to flag a `@Execution` as non-transactional, but meanwhile, you can wrap that inside the `@BeforeExecution`

```java
 @ChangeUnit(id = "create-photos-index", author = "Arthur Harkivsky", order = "001") 
public class CreatePhotosIndexChangeUnit {
     @BeforeExecution
     public void execution(final MongoTemplate template) {
         log.info("ChangeUnit 001 was started.");
         template.indexOps(VehicleAggregate.class)
                 .ensureIndex(new Index()
                         .named("photosIndex")
                         .on("photos", Sort.Direction.ASC));
         log.info("ChangeUnit 001 is finished.");
     }

     @RollbackBeforeExecution
     public void rollbackExecution(final MongoTemplate template) {
         log.info("ChangeUnit 001 rollback was started.");
         template.indexOps(VehicleAggregate.class)
                 .dropIndex("photosIndex");
         log.info("ChangeUnit rollback 001 is finished.");
     }
     
     
      @Execution
     public void execution(final MongoTemplate template) {
     }

     @RollbackExecution
     public void rollbackExecution(final MongoTemplate template) {
      }
 }
```

> Also be aware that the `ChangeUnits` are not autowired, so @Component doesn't do anything

**Comment by ArthurHarkivsky** [comment]
God bless you!!!
