### ISSUE TITLE
JHLite Spring Boot 3 - Mongock compatibility

### ISSUE THREAD

**Issue by dhivesh** [mongock/mongock#583]
**Title**
Mongock - Spring Boot 3 compatibility

**Description**
The JHipster team is upgrading JHLite to Spring Boot 3. This ticket is to support / track any issues with checking Mongock's compatibility with Spring Boot 3. 

The reference ticket in JHipster: https://github.com/jhipster/jhipster-lite/issues/3750 

**Priority:** Urgent

**Comment by pascalgrimaud** [comment]
thanks a lot, but no worry, it's not urgent, as it's open source project :-)

**Comment by dieppa** [comment]
Created a [repository](https://github.com/mongock/mongock-jdk17) for jdk17 modules, with only springboot-v3 and springdata-v4 in it for now.


The idea is that this repository inheritances from the mongock core and adds the modules for jdk17, without potential version mess.

**Comment by dieppa** [comment]
@atomfrede, I has added the springboot runner to the mongock-jdk17 project(for the time being, I just copied the code. We'll to refactor it to reuse the code)

Feel free to add the spring-data-4 code when you can. If it's causing you troubles, for the time being you can omit the `MongockTemplate` code. 

Thanks

**Comment by dieppa** [comment]
I closed it by too soon...now it can be closed 😄 

This has been resolved by creating(and releasing) two new arefacts: `io.mongock:mongock-springboot-v3` and `mongodb-springdata-v4-driver`

To use it:
1. Update mongock bom to 5.1.7
```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.mongock</groupId>
                <artifactId>mongock-bom</artifactId>
                <version>5.1.7</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
<!--...other dependencies-->
       </dependencies>
    </dependencyManagement>
```
2. If upgrading Mongock, remove runner and driver dependecies
3. Add springboot v3 runner and springdata v4 driver
```xml
<dependencies>
        <dependency>
            <groupId>io.mongock</groupId>
            <artifactId>mongock-springboot-v3</artifactId>
        </dependency>
        <dependency>
            <groupId>io.mongock</groupId>
            <artifactId>mongodb-springdata-v4-driver</artifactId>
        </dependency>
<!--...other dependencies-->
</dependencies>
```
