### ISSUE TITLE
missing io.mongock.runner.core.builder.RunnerBuilder bean when running migration through CLI

### ISSUE THREAD

**Issue by r-michal-ah** [mongock/mongock#598]
## Description

Hi @dieppa and @osantana85 I configured my project following this https://github.com/mongock/mongock-examples/tree/master/mongodb/springboot3-springdata4-jdk17 repository. 
When my Spring Boot application starts, migration is successful, this is fine. Unfortunately, running the same jar through CLI gives me:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field builder in io.mongock.cli.springboot.CliSpringbootRunner required a bean of type 'io.mongock.runner.core.builder.RunnerBuilder' that could not be found.

The injection point has the following annotations:
        - @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'io.mongock.runner.core.builder.RunnerBuilder' in your configuration.
```

## PRIORITY

[CRITICAL]

### Mongock
- Mongock version: 5.2.
- Modules involved: springboot and MongoDB
- How Mongock is used (builder or annotation approach): tried both without success.

### Environment
- Framework and libraries versions. Spring Boot 2.7.3, mongock-bom: 5.2.2, mongodb: 4.6.1
- Infrastructure: running locally 

## Steps to Reproduce

1. run: mvn clean package -DSkipTests
2. run: mongock migrate all -aj myJar.jar

## Behaviour

**Expected behavior:** I would expect that successful migration will happen.

**Actual behavior:** 

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field builder in io.mongock.cli.springboot.CliSpringbootRunner required a bean of type 'io.mongock.runner.core.builder.RunnerBuilder' that could not be found.

The injection point has the following annotations:
        - @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'io.mongock.runner.core.builder.RunnerBuilder' in your configuration.
```

**How often the bug happens:** 100%

## Link to repository using Mongock

[While not mandatory, accessing to the real code that uses Mongock, would help to solve the issue]

## Additional context

[Any additional information, logs, screenshots, configuration or data that might be necessary to reproduce or understand the issue]

**Comment by r-michal-ah** [comment]
@dieppa any update on that? Do you have any assumptions why it might happen?

**Comment by dieppa** [comment]
It' probably due to the fact that the builder is not injected correctly. It would help if you can build a project that I can access to reproducing the failure.

Otherwise it's a bit tricky.

Thanks

**Comment by osantana85** [comment]
Hello @r-michal-ah , we have test current CLI release with some of our examples (including springboot3 one) and it works fine. As @dieppa says, could you provide a project to allow us to reproduce the error? Thanks.

**Comment by osantana85** [comment]
Closed due to inactivity.
