### ISSUE TITLE
Documentation Issue: ChangeSet Javadoc

### ISSUE THREAD

**Issue by N4SoftwareNinja** [mongock/mongock#602]
## Description

In the JavaDoc of the deprecated ChangeSet annotation is the following recommended approach for new changeSets created with Mongock 5:

`For new changeLogs/changeSets created  from version 5: ChangeLogs/changeSets implement your changelogs by  implementing the interfaces ChangeLog or BasicChangeLog`

The mentioned interfaces do not exist and according to the documentation on the website, the Javadoc should point out to the @Execution and @RollbackExecution annotations or even easier point to the documentation on the website (https://docs.mongock.io/v5/migration/index.html)

## PRIORITY

MINOR

### Mongock
- Mongock version: current

**Comment by osantana85** [comment]
Fixed in version 5.2.4.
