### ISSUE TITLE
Releases at Github

### ISSUE THREAD

**Issue by LeovR** [mongock/mongock#611]
## Description

Is there a reason why newer releases, which are available via Maven, are not marked as releases in Github?

The latest release here https://github.com/mongock/mongock/releases is **5.1.0**.

But the latest Maven release is **5.2.4**.

**Comment by osantana85** [comment]
Hello @LeovR , there is no reason, you can use Mongock's version 5.2.4 (Maven central latest) with confidence. We'll update github asap. Thanks for raising this issue.
