### ISSUE TITLE
Migrations are not applied to DB. Also there is no logs related to mongock while running application

### ISSUE THREAD

**Issue by mariyajosh** [mongock/mongock#614]
## Description

[Description of the issue]

## PRIORITY
CRITICAL

[CRITICAL, NORMAL or MINOR]

## Version and environment
	id 'org.springframework.boot' version '3.1.0-SNAPSHOT'
### Mongock
        compileOnly 'io.mongock:mongock-springboot:5.2.4'
        implementation 'com.github.cloudyrock.mongock:mongodb-springdata-v3-driver:4.3.8'

### Environment
  Spring-data-mongodb

## Steps to Reproduce

1. After adding above dependencies.
2. create a changelog package and define sample change unit.
3. define changelog location in application.properties

**Comment by osantana85** [comment]
Hello @mariyajosh , it seems a problem related to Mongock's usage with Springboot v3. Mongock is compatible with Springboot v3, but at the moment only in combination with SpringData v4 Driver. Please take a look to this sample project:

[Springboot v3 + Springdata v4 - Sample Project (JDK17)](https://github.com/mongock/mongock-examples/tree/master/mongodb/springboot3-springdata4-jdk17)

Hope it helps you.
