### ISSUE TITLE
default-migration-author not applied in spring context

### ISSUE THREAD

**Issue by lnu** [mongock/mongock#631]
## Description

default-migration-author set in spring application properties is never applied

## PRIORITY

NORMAL

### Mongock
Mongock 5.2.1
Springboot 2.7
Mongock setup in spring using autoconfig
MongoDB

### Environment
local

## Steps to Reproduce

1. Setup a springboot app with spring
2. set the default-migration-author in application properties
3. add a changeunit
4. Check the author in the mongockChangelog collection

## Behaviour

**Expected behavior:** [What you expect to happen]

Having the default-migration-author configured in application properties to be the author of the changeunit in the mongockChangeLog collection

**Actual behavior:** [What actually happens]

Author is always `default_author`

**How often the bug happens:** [What percentage of the time does it reproduce?]

100%

## Link to repository using Mongock

[While not mandatory, accessing to the real code that uses Mongock, would help to solve the issue]

## Additional context

https://github.com/mongock/mongock/blob/423fa497477e3df7fca1799c4c1ac1cdb738b1b2/mongock-core/mongock-api/src/main/java/io/mongock/api/config/MongockConfiguration.java#L153

Author is not copied from the spring config to the base config

**Comment by dieppa** [comment]
Hello @lnu ,

we'll take a look at this as soon as possible. However, you are welcome to raise a pull request with this changes, it seems you could know how to fix it.

Thanks

**Comment by osantana85** [comment]
Released in Mongock's version 5.3.4. Thanks for your contribution.
