### ISSUE TITLE
BOM not published for version 5.3.5

### ISSUE THREAD

**Issue by oliverlockwood** [mongock/mongock#653]
Latest version of https://mvnrepository.com/artifact/io.mongock/mongock-bom is 5.3.4 (published 1st September 2023)

Latest version of e.g. https://mvnrepository.com/artifact/io.mongock/mongock-api is 5.3.5 (published 5th November 2023)

I assume this is in error.

**Comment by osantana85** [comment]
Hello @oliverlockwood , we have just released Mongock version 5.3.5, so now you can get the updated BOM artifact.

**Comment by oliverlockwood** [comment]
Thanks, @osantana85.
