### ISSUE TITLE
Overwriting index of a collection fails

### ISSUE THREAD

**Issue by anz000** [mongock/mongock#657]
I am using `Mongock v3.3.2` & `Spring Boot 2.1.4`.

I have an entity 'MyClass' that had an index on a field. I want to modify that index and add unique constraint to that index.

Previously:
```
@Document(collection = "myclass")
public class MyClass {
  ...
  @Indexed
  private String id;
  ..
}
```

New:
```
@Document(collection = "myclass")
public class MyClass {
  ...
  @Indexed(unique = true)
  private String id;
  ..
}
```

Since you have to drop the `index` first and create a new `index` that adjusts to the new `unique` constraint, I wanted to perform a Mongock migration to adjust the indexes. However, the application startup fails before running the migration complaining about the index already existing.

I tried using the standalone setup
```
     @Bean("mongock-standalone")
    public Mongock mongockStandalone() {
        String mongoDatabase = getDatabaseName(); // returns database based on current profile
        MongoClient mongoclient = mongoClient();

        Mongock runner = new MongockBuilder(mongoclient, mongoDatabase, "random.test.rawMigration")
                .setLockQuickConfig()
                .build();

        runner.execute();
        return runner;
    }
```
and attached a @DependsOn on the MyClass entity, but it doesn't work either.

I need the migration completed before Spring Boot starts to evaluate the classes. Any pointers would be much appreciated. Thanks.

**Comment by osantana85** [comment]
Hello @anz000 , you are using an old version of Mongock library. We'd recommend you to upgrade to latest version (currenty 5.3.6), for a better support.

In order to can help you we need some additional information, for example the code of the ChangeUnit (legacy ChangeLog/ChangeSet) you are using to execute that index recreation.

For further information you can take a look to Mongock's documentation. It includes migration guide to upgrade up to version 5.

Hope this helps you.

**Comment by osantana85** [comment]
Assuming you are working with auto-index-creation enabled (spring-data property), your application will create collections and related indexes at startup (before Mongock's execution take place). If you want to manage index creation with Mongock migrations, you should disable auto-index-creation. Could you try it?

**Comment by anz000** [comment]
It does if I disable the `auto-index-creation`. 

Is it not possible to run the Mongock migration once the MongoDB setup can be accessed and before it setsup the respective classes? I was hinting at the standalone setup. If it can be done with the standalone setup, I'd still need profile's specific mongoDB uri to perform the migration on.

**Comment by osantana85** [comment]
As you are using standalone  runner, you have the control of Mongock's execution. If Springboot / Springdata is initialized before Mongock's execution take place, it's a problem unrelated to Mongock, it's related to Springboot lifecycle.

A workaround you can try is to move the springdata configuration to a secondary class which depends on Mongock's runner bean, and maybe you can execute it before its initialization takes place. Could you try it? You should use `@DependsOn` in the configuration class and not in the entity.

**Comment by anz000** [comment]
We'll probably upgrade to `5.x` version of `Mongock`, and disable the `auto-index-creation` for `Spring-Data-MongoDB`.

I'll reopen if we need to have `auto-index-creation` enabled.

Thanks.
