### ISSUE TITLE
Executed Changelog treated as Not executed

### ISSUE THREAD

**Issue by pbusque-cgi** [mongock/mongock#677]
## Description

After adding a second Changelog in a newly created project on Mongock 5.4.2, they would always execute, in alternance, after each restart.  A new entry would be inserted in the mongockChangeLog table for each run.

## PRIORITY

CRITICAL

### Mongock
- Mongock version: 5.4.2
- Modules involved
  - Springboot
  - MongoDB
- How Mongock is used
  - @EnableMongock used in Springboot Application

### Environment
- Framework and libraries versions. Especially those that affect directly to Mongock(Spring, Spring data, MongoDB driver, etc.)
  - org.springframework.boot:spring-boot-starter-parent:3.2.4
  - io.mongock:mongock-bom:5.4.2
  - mongock-springboot-v3

- Infrastructure: 
  - Local Windows machine

## Steps to Reproduce

1. Create a blank Mongock Project
2. Create two changelogs with identical changeId, but different author. Ex: 
  @ChangeUnit(id = "createIndex", order = "1", author = "John")
  @ChangeUnit(id = "createIndex", order = "2", author = "Doe")
3. Run the Application. Both ChangeLog should run.
4. Restart the Application, Changelog for John should run again. 
5. Restart the Application, Changelog for Doe should run again.
6. Restart the Application, Changelog for John should run again.

## Behaviour

**Expected behavior:**
Changelog unit should only run ONCE.

**Actual behavior:** 
ChangeLog run in alternate, 

**How often the bug happens:** 
Always when two or more changelog have the same ID but different author.

## Additional context

I did my own investigation.
Mongock is calling io.mongock.driver.api.entry.ChangeEntryService.getExecuted() to retrieve a list of executed ChangeEntry.
Then it loop through this list to locate an ChangeEntry with the matching ID and Author.

However, getExecuted is using EntriesMap, which group all ChangeEntry by ID.
If multiple Changelog with the same ID but different Author exist, they get put under the same ID.
When getExecuted run, it filter Ignored, failed and rollbacked_fail entries, then KEEP the first one, discarting the other ChangeEntry that may have sucessfully ran under a different author.

` default List<ChangeEntryExecuted> getExecuted() throws MongockException {

    Predicate<ChangeEntry> cleanIrrelevantState = entry -> entry.getState() != IGNORED && entry.getState() != FAILED && entry.getState() != ROLLBACK_FAILED;
    return getEntriesMap()//Maps of List<ChangeEntry>, indexed by changeId
        .values()//collection of List<ChangeEntry>
        .stream()
        .map(duplicatedEntries -> duplicatedEntries.stream().filter(cleanIrrelevantState).collect(Collectors.toList()))//only takes into account executed or rolled back
        .filter(duplicatedEntries -> !duplicatedEntries.isEmpty())
        **.map(duplicatedEntries -> duplicatedEntries.get(0))//transform each list in a single ChangeEntry(the first one)**
        .sorted(Comparator.comparing(ChangeEntry::getOriginalTimestamp))// Sorts the resulting list chronologically
        .filter(ChangeEntry::isExecuted)//only gets the ones that are executed
        .map(ChangeEntryExecuted::new)//transform the entry to an executed entry
        .collect(Collectors.toList());
  }`

As a result, only the latest execution will be visible, all the other ones will be missing, treated as NOT executed and will be executed. As Mongock run the changelog, it inject another entry in the mongockChangeLog collection.  This execution become the newest EXECUTED.
As it run again, the other Changelog get ignored, become to be executed, and inject itself as the newest EXECUTED.
And the loop goes on.

**How to Fix.:** 
I do not understand the reason why the List of ChangeEntry got 'flattened' by grabing the first value.  All executed Entry should be kept.

` default List<ChangeEntryExecuted> getExecuted() throws MongockException {

    Predicate<ChangeEntry> cleanIrrelevantState = entry -> entry.getState() != IGNORED && entry.getState() != FAILED && entry.getState() != ROLLBACK_FAILED;
    return getEntriesMap()//Maps of List<ChangeEntry>, indexed by changeId
        .values()//collection of List<ChangeEntry>
        .stream()
        .map(duplicatedEntries -> duplicatedEntries.stream().filter(cleanIrrelevantState).collect(Collectors.toList()))//only takes into account executed or rolled back
        .filter(duplicatedEntries -> !duplicatedEntries.isEmpty())
        **.flatMap(List::stream)**
        .sorted(Comparator.comparing(ChangeEntry::getOriginalTimestamp))// Sorts the resulting list chronologically
        .filter(ChangeEntry::isExecuted)//only gets the ones that are executed
        .map(ChangeEntryExecuted::new)//transform the entry to an executed entry
        .collect(Collectors.toList());
  }`

Or a more intelligent filtering of other issued have to be removed.  But in the current situation, different author get discarted, breaking the ID + AUTHOR as being unique.

**Comment by osantana85** [comment]
Hello @pbusque-cgi , thanks for raising the issue. We'll take a look and let you know.

**Comment by pbusque-cgi** [comment]
Thanks.
I have added extra information, including a test case to reproduce the issue
Two ChangeUnit sharing the same ID but different AUTHOR  in a small Springboot application.

I ran it 5 times, and you can see multiple enties in the "mongockChangeLog" collection while there should only be 2 (first executions).
[mongock.zip](https://github.com/user-attachments/files/15777735/mongock.zip)
![Capture d’écran 2024-06-10 143805](https://github.com/mongock/mongock/assets/172076529/80f704e6-1d95-4c79-baef-d3461471ac80)
![Capture d’écran 2024-06-10 143824](https://github.com/mongock/mongock/assets/172076529/98c70a0e-67f5-480c-904e-b2ffa9b9da32)
![Capture d’écran 2024-06-10 143853](https://github.com/mongock/mongock/assets/172076529/bb30ce06-fe0a-4006-a146-9e9aa5753c7f)
![Capture d’écran 2024-06-10 143928](https://github.com/mongock/mongock/assets/172076529/68d48e7c-9f12-48b2-a780-712a2859646c)

**Comment by osantana85** [comment]
Fixed in Mongock v5.5.0.
