### ISSUE TITLE
The Apache Commons Lang 3 library is directly used but not declared in the maven dependencies

### ISSUE THREAD

**Issue by tms0** [mongock/mongock#679]
## Description

Hi,

I am the maintainer of the Mongock extension for Quarkus (https://github.com/quarkiverse/quarkus-mongock). Since yesterday, the build is broken with the latest Quarkus sources (https://github.com/quarkiverse/quarkus-mongock/actions/runs/9576475159). Looking at the logs, there is an issue while building the GraalVM native executable :
```
2024-06-19T08:03:44.7572031Z Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.apache.commons.lang3.StringUtils. This error is reported at image build time because class io.mongock.runner.core.executor.ChangeExecutorBase is registered for linking at image build time by command line and command line.
```

I saw that the Apache Commons Lang 3 library is directly used by Mongock (https://github.com/mongock/mongock/blob/951dd9f67c282666c26fd1f4f2bf60f19e60d0b0/mongock-core/mongock-runner/mongock-runner-core/src/main/java/io/mongock/runner/core/executor/ChangeExecutorBase.java#L19) but is not declared in the maven dependencies.

I guess it was luckily included transitively, but for any reason this is no longer the case with the latest Quarkus sources. I did not push the analysis further though.

In any case, I think it's a good practice to declare every dependencies directly used by the projet. What do you think about it ?

## PRIORITY

NORMAL

### Mongock
- Mongock version : latest

### Environment
- Framework and libraries versions : Quarkus (snapshot version)

**Comment by osantana85** [comment]
Fixed in Mongock v5.5.0 (was removed unnecessary dependency causing the problem).
