### ISSUE TITLE
Update mongdb-sync-driver for Spring Boot 3.3.X

### ISSUE THREAD

**Issue by alberrogu** [mongock/mongock#685]
## Description

We need to add support for Spring Boot 3.3.X. The dependency for the mongo-sync driver has been updated to version 5.0.1, which requires compatibility with Spring Boot 3.3.X

## PRIORITY

NORMAL

## Version and environment

Spring Boot 3.3.2 and mongock 5.4.4

### Mongock
- Mongock 5.4.4
- mongodb-springdata-v3-driver

### Environment
- Spring boot 3.3.0

**Comment by rfelgent** [comment]
the same here. I can confirm, that mongock 5.4.0 (and higher) is compatible with spring boot 3.3.x

@osantana85 can we close this issue ?

**Comment by osantana85** [comment]
@rfelgent  Closed, thanks.
