### ISSUE TITLE
Is DynamoDB support to be deprecated after 2025?

### ISSUE THREAD

**Issue by gthoma17** [mongock/mongock#690]
## Description

The AWS SDK for Java v1.x upon which the [Mongock DynamoDB Driver](https://github.com/mongock/mongock-driver-dynamodb) is built entered maintenance mode on July 31, 2024, and will reach end-of-support on December 31, 2025.[1]

Are there plans to updated to the AWS SDK for Java v2.x, or will DynamoDB no longer be supported by Mongock after 2025? 

If so, I would be interested in contributing, but I also notice that the repo for the driver was archived on Apr 1, 2022.

## PRIORITY

NORMAL

### Mongock
- Modules involved: DynamoDB Driver 5.4.4, DynamoDB SpringBoot Driver 5.4.4

## Additional context

1: https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/

**Comment by osantana85** [comment]
Hello @gthoma17 , we are working in a new major release which be updated to use AWS SDK for Java v2.x, so yes, it will be supported by Mongock.

Thanks
