### ISSUE TITLE
Start mongock in parallel

### ISSUE THREAD

**Issue by sorushi97** [mongock/mongock#692]
A common scenario is a SaaS product in which, instead of having a shared database for all the clients, each has its own and independent database(in the same or different server), but sharing the same source code and deployment. In this case, you would want to apply the same Mongock migration to each client's database.The application is configured to work with N datasources and Mongock runs the migration for all of them(sequentially)

I want to trigger the changeset parallelly so for 2 different dB it will async but within same dB it will execute sequentially as per id

**Comment by osantana85** [comment]
Hi @sorushi97 , Mongock currently doesn't offer parallel execution out of the box, but we're working on a new major release that will include several important features, and a new workflow with parallel execution is on the roadmap.

In the meantime, you can try to implement a workaround on your own, using the Mongock builder approach and creating as many Mongock instances as the application has datasources, starting each instance in a separate thread (and managing them).

I'm aware that it's a bit complicated, so it depends on your actual needs.

Hope this helps.
